// Generated by CoffeeScript 1.6.3
var inWords;

module.exports = function(since, till) {
  if (till == null) {
    till = new Date();
  }
  return inWords(till.getTime() - since.getTime());
};

module.exports.settings = {
  allowFuture: false,
  prefixAgo: null,
  prefixFromNow: null,
  suffixAgo: "ago",
  suffixFromNow: "from now",
  seconds: "less than a minute",
  minute: "about a minute",
  minutes: "%d minutes",
  hour: "about an hour",
  hours: "about %d hours",
  day: "a day",
  days: "%d days",
  month: "about a month",
  months: "%d months",
  year: "about a year",
  years: "%d years",
  numbers: []
};

inWords = function(distanceMillis) {
  var days, hours, minutes, prefix, seconds, settings, substitute, suffix, words, years;
  settings = module.exports.settings;
  substitute = function(stringOrFunction, number) {
    var string, value;
    string = (typeof stringOrFunction === "function" ? stringOrFunction(number, distanceMillis) : stringOrFunction);
    value = (settings.numbers && settings.numbers[number]) || number;
    return string.replace(/%d/i, value);
  };
  prefix = settings.prefixAgo;
  suffix = settings.suffixAgo;
  if (settings.allowFuture) {
    if (distanceMillis < 0) {
      prefix = settings.prefixFromNow;
      suffix = settings.suffixFromNow;
    }
  }
  seconds = Math.abs(distanceMillis) / 1000;
  minutes = seconds / 60;
  hours = minutes / 60;
  days = hours / 24;
  years = days / 365;
  words = seconds < 45 && substitute(settings.seconds, Math.round(seconds)) || seconds < 90 && substitute(settings.minute, 1) || minutes < 45 && substitute(settings.minutes, Math.round(minutes)) || minutes < 90 && substitute(settings.hour, 1) || hours < 24 && substitute(settings.hours, Math.round(hours)) || hours < 48 && substitute(settings.day, 1) || days < 30 && substitute(settings.days, Math.floor(days)) || days < 60 && substitute(settings.month, 1) || days < 365 && substitute(settings.months, Math.floor(days / 30)) || years < 2 && substitute(settings.year, 1) || substitute(settings.years, Math.floor(years));
  return [prefix, words, suffix].join(" ").toString().trim();
};
