// Generated by CoffeeScript 1.6.3
var inWords, translate;

module.exports = function(since, o) {
  if (since == null) {
    since = new Date();
  }
  if (o == null) {
    o = {};
  }
  o.till = o.till || new Date();
  o.language = o.language || 'en';
  return inWords(o.till.getTime() - since.getTime(), o.language);
};

module.exports.settings = {
  allowFuture: false,
  prefixAgo: null,
  prefixFromNow: null,
  numbers: [],
  suffixAgo: "ago",
  suffixFromNow: "from now",
  seconds: "less than a minute",
  minute: "about a minute",
  minutes: "%d minutes",
  hour: "about an hour",
  hours: "about %d hours",
  day: "a day",
  days: "%d days",
  month: "about a month",
  months: "%d months",
  year: "about a year",
  years: "%d years"
};

inWords = function(distanceMillis, ln) {
  var days, hours, key, minutes, prefix, seconds, settings, substitute, suffix, translations, words, years;
  if (ln == null) {
    ln = 'en';
  }
  settings = module.exports.settings;
  if (ln !== 'en') {
    translations = translate(ln);
    for (key in translations) {
      settings[key] = translations[key];
    }
  }
  substitute = function(stringOrFunction, number) {
    var string, value;
    string = (typeof stringOrFunction === "function" ? stringOrFunction(number, distanceMillis) : stringOrFunction);
    value = (settings.numbers && settings.numbers[number]) || number;
    return string.replace(/%d/i, value);
  };
  prefix = settings.prefixAgo;
  suffix = settings.suffixAgo;
  if (settings.allowFuture) {
    if (distanceMillis < 0) {
      prefix = settings.prefixFromNow;
      suffix = settings.suffixFromNow;
    }
  }
  seconds = Math.abs(distanceMillis) / 1000;
  minutes = seconds / 60;
  hours = minutes / 60;
  days = hours / 24;
  years = days / 365;
  words = seconds < 45 && substitute(settings.seconds, Math.round(seconds)) || seconds < 90 && substitute(settings.minute, 1) || minutes < 45 && substitute(settings.minutes, Math.round(minutes)) || minutes < 90 && substitute(settings.hour, 1) || hours < 24 && substitute(settings.hours, Math.round(hours)) || hours < 48 && substitute(settings.day, 1) || days < 30 && substitute(settings.days, Math.floor(days)) || days < 60 && substitute(settings.month, 1) || days < 365 && substitute(settings.months, Math.floor(days / 30)) || years < 2 && substitute(settings.year, 1) || substitute(settings.years, Math.floor(years));
  return [prefix, words, suffix].join(" ").toString().trim();
};

translate = function(ln) {
  if (ln === 'pt') {
    return {
      suffixAgo: "",
      suffixFromNow: "agora",
      seconds: "menos de um minuto",
      minute: "aproximadamente um minuto",
      minutes: "%d minutos",
      hour: "aproximadamente uma hora",
      hours: "aproximadamente %d horas",
      day: "um dia",
      days: "%d dias",
      month: "aproximadamente um mês",
      months: "%d meses",
      year: "aproximadamente um ano",
      years: "%d anos"
    };
  } else {
    return {};
  }
};
